### ISSUE TITLE
Attributes not imported (STR, DEX, etc.)

### ISSUE THREAD

**Issue by CScarlett** [MrPrimate/pathmuncher#28]
They're all +0

**Comment by MrPrimate** [comment]
I'm going to close this issue, as it works here, if you still experience the problem, please add more details as originally requested when you open a `bug` issue, so I can try and replicate it:


**Environment:**
 - Browser [e.g. chrome]
 - Foundry Version [e.g. 10.288]
 - Pathfinder System Version [e.g 2.0.3]
 - Module Version [e.g 3.1.21]
 - Does this behaviour occur with other modules disabled: Yes/No (Find The Culprit module can help with this)

**Additional context**
Add any other context about the problem here.

 - In Pathbuilder please got to Export -> "Share Copy of Character" and provide the link.
 - Details of any errors in the browser console (press F12).

**Comment by MrPrimate** [comment]
Another user provided some more details, please see a fix in v0.11.1
